/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Winter Melon
 */
public class FinanceModule extends javax.swing.JPanel {

    /**
     * Creates new form FinanceModule
     */
    public FinanceModule() {
        initComponents();
    }
    
    public javax.swing.JTabbedPane getTabPane() {
    return tabFinanceModule; 
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabFinanceModule = new javax.swing.JTabbedPane();
        pnlPayrollRecords = new javax.swing.JPanel();
        pnlPayrollRecCtrl = new javax.swing.JPanel();
        txtPayrollRecSearch = new javax.swing.JTextField();
        drpPayrollRecMonth = new javax.swing.JComboBox<>();
        drpPayrollRecPeriod = new javax.swing.JComboBox<>();
        drpPayrollRecYear = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        pnlPayrollRecRow1 = new javax.swing.JPanel();
        lblPayrollRecID = new javax.swing.JLabel();
        txtPayrollRecEID = new javax.swing.JLabel();
        lblPayrollRecName = new javax.swing.JLabel();
        txtPayrollRecName = new javax.swing.JLabel();
        lblPayrollRecDate = new javax.swing.JLabel();
        txtPayrollRecDate = new javax.swing.JLabel();
        pnlPayrollRecVGlue4 = new javax.swing.JLabel();
        pnlPayrollRecRow2 = new javax.swing.JPanel();
        pnlPayrollRecEarnings = new javax.swing.JPanel();
        lblBasicPay = new javax.swing.JLabel();
        txtBasicPay = new javax.swing.JLabel();
        lblAllowancePay = new javax.swing.JLabel();
        txtAllowancePay = new javax.swing.JLabel();
        lblOvertimePay = new javax.swing.JLabel();
        txtOvertimePay = new javax.swing.JLabel();
        vGlue9 = new javax.swing.JLabel();
        pnlPayrollRecDeductions = new javax.swing.JPanel();
        lblLateDeduc = new javax.swing.JLabel();
        txtLateDeduc = new javax.swing.JLabel();
        lblTaxDeduc = new javax.swing.JLabel();
        txtTaxDeduc = new javax.swing.JLabel();
        lblSSSDeduc = new javax.swing.JLabel();
        txtSSSDeduc = new javax.swing.JLabel();
        lblPhilHealthDeduc = new javax.swing.JLabel();
        txtPhilHealthDeduc = new javax.swing.JLabel();
        lblPagibigDeduc = new javax.swing.JLabel();
        txtPagibigDeduc = new javax.swing.JLabel();
        vGlue10 = new javax.swing.JLabel();
        pnlPayrollRecVGlue5 = new javax.swing.JLabel();
        pnlPayrollRecRow3 = new javax.swing.JPanel();
        pnlPayrollRecSummary = new javax.swing.JPanel();
        lblGrossPay = new javax.swing.JLabel();
        txtGrossPay = new javax.swing.JLabel();
        lblTotalDeductions = new javax.swing.JLabel();
        txtTotalDeductions = new javax.swing.JLabel();
        lblNetPay = new javax.swing.JLabel();
        txtNetPay = new javax.swing.JLabel();
        vGlue11 = new javax.swing.JLabel();
        pnlPayrollRecVGlue6 = new javax.swing.JLabel();
        pnlPayrollRecVGlue7 = new javax.swing.JLabel();
        pnlStatutory = new javax.swing.JPanel();
        lblStatutoryNotice = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlPayrollRecords.setLayout(new java.awt.BorderLayout());

        pnlPayrollRecCtrl.setBackground(new java.awt.Color(255, 255, 255));

        txtPayrollRecSearch.setText("Employee ID");
        txtPayrollRecSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        txtPayrollRecSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPayrollRecSearchKeyTyped(evt);
            }
        });
        pnlPayrollRecCtrl.add(txtPayrollRecSearch);

        drpPayrollRecMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Month]", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        drpPayrollRecMonth.setPreferredSize(new java.awt.Dimension(150, 30));
        drpPayrollRecMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpPayrollRecMonthActionPerformed(evt);
            }
        });
        pnlPayrollRecCtrl.add(drpPayrollRecMonth);

        drpPayrollRecPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Period]", "1st - 15th", "16th - End" }));
        drpPayrollRecPeriod.setPreferredSize(new java.awt.Dimension(150, 30));
        drpPayrollRecPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpPayrollRecPeriodActionPerformed(evt);
            }
        });
        pnlPayrollRecCtrl.add(drpPayrollRecPeriod);

        drpPayrollRecYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Year]", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        drpPayrollRecYear.setPreferredSize(new java.awt.Dimension(150, 30));
        pnlPayrollRecCtrl.add(drpPayrollRecYear);

        pnlPayrollRecords.add(pnlPayrollRecCtrl, java.awt.BorderLayout.NORTH);

        jScrollPane8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        pnlPayrollRecRow1.setBackground(new java.awt.Color(255, 255, 255));
        pnlPayrollRecRow1.setLayout(new java.awt.GridBagLayout());

        lblPayrollRecID.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPayrollRecID.setForeground(new java.awt.Color(140, 140, 140));
        lblPayrollRecID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPayrollRecID.setText("Employee ID:");
        lblPayrollRecID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecRow1.add(lblPayrollRecID, gridBagConstraints);

        txtPayrollRecEID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPayrollRecEID.setForeground(new java.awt.Color(30, 30, 30));
        txtPayrollRecEID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPayrollRecEID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecRow1.add(txtPayrollRecEID, gridBagConstraints);

        lblPayrollRecName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPayrollRecName.setForeground(new java.awt.Color(140, 140, 140));
        lblPayrollRecName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPayrollRecName.setText("Name:");
        lblPayrollRecName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecRow1.add(lblPayrollRecName, gridBagConstraints);

        txtPayrollRecName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPayrollRecName.setForeground(new java.awt.Color(30, 30, 30));
        txtPayrollRecName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPayrollRecName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecRow1.add(txtPayrollRecName, gridBagConstraints);

        lblPayrollRecDate.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPayrollRecDate.setForeground(new java.awt.Color(140, 140, 140));
        lblPayrollRecDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPayrollRecDate.setText("Date Covered:");
        lblPayrollRecDate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecRow1.add(lblPayrollRecDate, gridBagConstraints);

        txtPayrollRecDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPayrollRecDate.setForeground(new java.awt.Color(30, 30, 30));
        txtPayrollRecDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPayrollRecDate.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecRow1.add(txtPayrollRecDate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        pnlPayrollRecRow1.add(pnlPayrollRecVGlue4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 20);
        jPanel2.add(pnlPayrollRecRow1, gridBagConstraints);

        pnlPayrollRecRow2.setBackground(new java.awt.Color(255, 255, 255));
        pnlPayrollRecRow2.setLayout(new java.awt.GridBagLayout());

        pnlPayrollRecEarnings.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Earnings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15))); // NOI18N
        pnlPayrollRecEarnings.setMinimumSize(new java.awt.Dimension(10, 10));
        pnlPayrollRecEarnings.setOpaque(false);
        pnlPayrollRecEarnings.setLayout(new java.awt.GridBagLayout());

        lblBasicPay.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblBasicPay.setForeground(new java.awt.Color(140, 140, 140));
        lblBasicPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBasicPay.setText("Basic Pay:");
        lblBasicPay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecEarnings.add(lblBasicPay, gridBagConstraints);

        txtBasicPay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBasicPay.setForeground(new java.awt.Color(30, 30, 30));
        txtBasicPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtBasicPay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecEarnings.add(txtBasicPay, gridBagConstraints);

        lblAllowancePay.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblAllowancePay.setForeground(new java.awt.Color(140, 140, 140));
        lblAllowancePay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAllowancePay.setText("Allowances:");
        lblAllowancePay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecEarnings.add(lblAllowancePay, gridBagConstraints);

        txtAllowancePay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAllowancePay.setForeground(new java.awt.Color(30, 30, 30));
        txtAllowancePay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtAllowancePay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecEarnings.add(txtAllowancePay, gridBagConstraints);

        lblOvertimePay.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblOvertimePay.setForeground(new java.awt.Color(140, 140, 140));
        lblOvertimePay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOvertimePay.setText("Hourly Rate:");
        lblOvertimePay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecEarnings.add(lblOvertimePay, gridBagConstraints);

        txtOvertimePay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOvertimePay.setForeground(new java.awt.Color(30, 30, 30));
        txtOvertimePay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtOvertimePay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecEarnings.add(txtOvertimePay, gridBagConstraints);

        vGlue9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vGlue9.setForeground(new java.awt.Color(30, 30, 30));
        vGlue9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vGlue9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlPayrollRecEarnings.add(vGlue9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlPayrollRecRow2.add(pnlPayrollRecEarnings, gridBagConstraints);

        pnlPayrollRecDeductions.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deductions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15))); // NOI18N
        pnlPayrollRecDeductions.setMinimumSize(new java.awt.Dimension(10, 10));
        pnlPayrollRecDeductions.setOpaque(false);
        pnlPayrollRecDeductions.setLayout(new java.awt.GridBagLayout());

        lblLateDeduc.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblLateDeduc.setForeground(new java.awt.Color(140, 140, 140));
        lblLateDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLateDeduc.setText("Late:");
        lblLateDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecDeductions.add(lblLateDeduc, gridBagConstraints);

        txtLateDeduc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLateDeduc.setForeground(new java.awt.Color(30, 30, 30));
        txtLateDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtLateDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecDeductions.add(txtLateDeduc, gridBagConstraints);

        lblTaxDeduc.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTaxDeduc.setForeground(new java.awt.Color(140, 140, 140));
        lblTaxDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTaxDeduc.setText("Withholding Tax:");
        lblTaxDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecDeductions.add(lblTaxDeduc, gridBagConstraints);

        txtTaxDeduc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTaxDeduc.setForeground(new java.awt.Color(30, 30, 30));
        txtTaxDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTaxDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecDeductions.add(txtTaxDeduc, gridBagConstraints);

        lblSSSDeduc.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblSSSDeduc.setForeground(new java.awt.Color(140, 140, 140));
        lblSSSDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSSSDeduc.setText("SSS:");
        lblSSSDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecDeductions.add(lblSSSDeduc, gridBagConstraints);

        txtSSSDeduc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSSSDeduc.setForeground(new java.awt.Color(30, 30, 30));
        txtSSSDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSSSDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecDeductions.add(txtSSSDeduc, gridBagConstraints);

        lblPhilHealthDeduc.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPhilHealthDeduc.setForeground(new java.awt.Color(140, 140, 140));
        lblPhilHealthDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhilHealthDeduc.setText("PhilHealth:");
        lblPhilHealthDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecDeductions.add(lblPhilHealthDeduc, gridBagConstraints);

        txtPhilHealthDeduc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhilHealthDeduc.setForeground(new java.awt.Color(30, 30, 30));
        txtPhilHealthDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPhilHealthDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecDeductions.add(txtPhilHealthDeduc, gridBagConstraints);

        lblPagibigDeduc.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPagibigDeduc.setForeground(new java.awt.Color(140, 140, 140));
        lblPagibigDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPagibigDeduc.setText("Pagibig:");
        lblPagibigDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecDeductions.add(lblPagibigDeduc, gridBagConstraints);

        txtPagibigDeduc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPagibigDeduc.setForeground(new java.awt.Color(30, 30, 30));
        txtPagibigDeduc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPagibigDeduc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecDeductions.add(txtPagibigDeduc, gridBagConstraints);

        vGlue10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vGlue10.setForeground(new java.awt.Color(30, 30, 30));
        vGlue10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vGlue10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlPayrollRecDeductions.add(vGlue10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlPayrollRecRow2.add(pnlPayrollRecDeductions, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        pnlPayrollRecRow2.add(pnlPayrollRecVGlue5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 20);
        jPanel2.add(pnlPayrollRecRow2, gridBagConstraints);

        pnlPayrollRecRow3.setBackground(new java.awt.Color(255, 255, 255));
        pnlPayrollRecRow3.setLayout(new java.awt.GridBagLayout());

        pnlPayrollRecSummary.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pay Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15))); // NOI18N
        pnlPayrollRecSummary.setMinimumSize(new java.awt.Dimension(10, 10));
        pnlPayrollRecSummary.setOpaque(false);
        pnlPayrollRecSummary.setLayout(new java.awt.GridBagLayout());

        lblGrossPay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGrossPay.setForeground(new java.awt.Color(140, 140, 140));
        lblGrossPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGrossPay.setText("Gross Pay:");
        lblGrossPay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecSummary.add(lblGrossPay, gridBagConstraints);

        txtGrossPay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGrossPay.setForeground(new java.awt.Color(30, 30, 30));
        txtGrossPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtGrossPay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecSummary.add(txtGrossPay, gridBagConstraints);

        lblTotalDeductions.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalDeductions.setForeground(new java.awt.Color(140, 140, 140));
        lblTotalDeductions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalDeductions.setText("Tota Deductions:");
        lblTotalDeductions.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecSummary.add(lblTotalDeductions, gridBagConstraints);

        txtTotalDeductions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalDeductions.setForeground(new java.awt.Color(30, 30, 30));
        txtTotalDeductions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTotalDeductions.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecSummary.add(txtTotalDeductions, gridBagConstraints);

        lblNetPay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNetPay.setForeground(new java.awt.Color(140, 140, 140));
        lblNetPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNetPay.setText("Net Pay:");
        lblNetPay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        pnlPayrollRecSummary.add(lblNetPay, gridBagConstraints);

        txtNetPay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNetPay.setForeground(new java.awt.Color(30, 30, 30));
        txtNetPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNetPay.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        pnlPayrollRecSummary.add(txtNetPay, gridBagConstraints);

        vGlue11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vGlue11.setForeground(new java.awt.Color(30, 30, 30));
        vGlue11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vGlue11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlPayrollRecSummary.add(vGlue11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlPayrollRecRow3.add(pnlPayrollRecSummary, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        pnlPayrollRecRow3.add(pnlPayrollRecVGlue6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel2.add(pnlPayrollRecRow3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(pnlPayrollRecVGlue7, gridBagConstraints);

        jScrollPane8.setViewportView(jPanel2);

        pnlPayrollRecords.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        tabFinanceModule.addTab("Payroll Records", pnlPayrollRecords);

        lblStatutoryNotice.setText("FOR FUTURE IMPLEMENTATIONS -- EDITING OF DEDUCTION TABLES!");

        javax.swing.GroupLayout pnlStatutoryLayout = new javax.swing.GroupLayout(pnlStatutory);
        pnlStatutory.setLayout(pnlStatutoryLayout);
        pnlStatutoryLayout.setHorizontalGroup(
            pnlStatutoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatutoryLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblStatutoryNotice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStatutoryLayout.setVerticalGroup(
            pnlStatutoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatutoryLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblStatutoryNotice)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        tabFinanceModule.addTab("Deduction Tables", pnlStatutory);

        add(tabFinanceModule, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPayrollRecSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayrollRecSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayrollRecSearchKeyTyped

    private void drpPayrollRecMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpPayrollRecMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpPayrollRecMonthActionPerformed

    private void drpPayrollRecPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpPayrollRecPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpPayrollRecPeriodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> drpPayrollRecMonth;
    private javax.swing.JComboBox<String> drpPayrollRecPeriod;
    private javax.swing.JComboBox<String> drpPayrollRecYear;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblAllowancePay;
    private javax.swing.JLabel lblBasicPay;
    private javax.swing.JLabel lblGrossPay;
    private javax.swing.JLabel lblLateDeduc;
    private javax.swing.JLabel lblNetPay;
    private javax.swing.JLabel lblOvertimePay;
    private javax.swing.JLabel lblPagibigDeduc;
    private javax.swing.JLabel lblPayrollRecDate;
    private javax.swing.JLabel lblPayrollRecID;
    private javax.swing.JLabel lblPayrollRecName;
    private javax.swing.JLabel lblPhilHealthDeduc;
    private javax.swing.JLabel lblSSSDeduc;
    private javax.swing.JLabel lblStatutoryNotice;
    private javax.swing.JLabel lblTaxDeduc;
    private javax.swing.JLabel lblTotalDeductions;
    private javax.swing.JPanel pnlPayrollRecCtrl;
    private javax.swing.JPanel pnlPayrollRecDeductions;
    private javax.swing.JPanel pnlPayrollRecEarnings;
    private javax.swing.JPanel pnlPayrollRecRow1;
    private javax.swing.JPanel pnlPayrollRecRow2;
    private javax.swing.JPanel pnlPayrollRecRow3;
    private javax.swing.JPanel pnlPayrollRecSummary;
    private javax.swing.JLabel pnlPayrollRecVGlue4;
    private javax.swing.JLabel pnlPayrollRecVGlue5;
    private javax.swing.JLabel pnlPayrollRecVGlue6;
    private javax.swing.JLabel pnlPayrollRecVGlue7;
    private javax.swing.JPanel pnlPayrollRecords;
    private javax.swing.JPanel pnlStatutory;
    private javax.swing.JTabbedPane tabFinanceModule;
    private javax.swing.JLabel txtAllowancePay;
    private javax.swing.JLabel txtBasicPay;
    private javax.swing.JLabel txtGrossPay;
    private javax.swing.JLabel txtLateDeduc;
    private javax.swing.JLabel txtNetPay;
    private javax.swing.JLabel txtOvertimePay;
    private javax.swing.JLabel txtPagibigDeduc;
    private javax.swing.JLabel txtPayrollRecDate;
    private javax.swing.JLabel txtPayrollRecEID;
    private javax.swing.JLabel txtPayrollRecName;
    private javax.swing.JTextField txtPayrollRecSearch;
    private javax.swing.JLabel txtPhilHealthDeduc;
    private javax.swing.JLabel txtSSSDeduc;
    private javax.swing.JLabel txtTaxDeduc;
    private javax.swing.JLabel txtTotalDeductions;
    private javax.swing.JLabel vGlue10;
    private javax.swing.JLabel vGlue11;
    private javax.swing.JLabel vGlue9;
    // End of variables declaration//GEN-END:variables
}
