/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Winter Melon
 */
public class HRModule extends javax.swing.JPanel {

    /**
     * Creates new form HRModule
     */
    public HRModule() {
        initComponents();
    }
    
    public javax.swing.JTabbedPane getTabPane() {
    return tabHRModule; 
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHRModule = new javax.swing.JPanel();
        tabHRModule = new javax.swing.JTabbedPane();
        pnlEmpManage = new javax.swing.JPanel();
        pnlEmpManageCtrl = new javax.swing.JPanel();
        pnlEmpManageSearch = new javax.swing.JPanel();
        lblEmpManageSearch = new javax.swing.JLabel();
        txtEmpManageSearch = new javax.swing.JTextField();
        btnEmpManageSearch = new javax.swing.JButton();
        pnlEmpManageButtons = new javax.swing.JPanel();
        btnEmpManageAdd = new javax.swing.JButton();
        btnEmpManageEdit = new javax.swing.JButton();
        btnEmpManageDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpManageList = new javax.swing.JTable();
        pnlAttendanceRecords = new javax.swing.JPanel();
        pnlAttendanceRecCtrl = new javax.swing.JPanel();
        txtAttendanceSearch = new javax.swing.JTextField();
        drpAttendanceMonth = new javax.swing.JComboBox<>();
        drpAttendanceYear = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAttendanceRec = new javax.swing.JTable();
        pnlLeaveRecords = new javax.swing.JPanel();
        pnlLeaveRecCtrl = new javax.swing.JPanel();
        txtLeaveRecSearch = new javax.swing.JTextField();
        drpLeaveRecMonth = new javax.swing.JComboBox<>();
        drpLeaveRecYear = new javax.swing.JComboBox<>();
        drpLeaveRecStatus = new javax.swing.JComboBox<>();
        pnlPLeaveRecVGlue9 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblLeaveRec = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        pnlLeaveRecMsg = new javax.swing.JPanel();
        pnlLeaveRecReason = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtLeaveRecReason = new javax.swing.JTextArea();
        vGlue12 = new javax.swing.JLabel();
        pnlLeaveRecDecision = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtLeaveRecDecision = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btnLeaveRecApprove = new javax.swing.JButton();
        btnLeaveRecReject = new javax.swing.JButton();
        vGlue13 = new javax.swing.JLabel();
        pnlLeaveRecVGlue8 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlHRModule.setLayout(new java.awt.BorderLayout());

        pnlEmpManage.setLayout(new java.awt.BorderLayout());

        pnlEmpManageCtrl.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmpManageCtrl.setLayout(new java.awt.BorderLayout());

        pnlEmpManageSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlEmpManageSearch.setOpaque(false);
        pnlEmpManageSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        lblEmpManageSearch.setText("Search Employee ID:");
        pnlEmpManageSearch.add(lblEmpManageSearch);

        txtEmpManageSearch.setText("Employee ID");
        txtEmpManageSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        txtEmpManageSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpManageSearchKeyTyped(evt);
            }
        });
        pnlEmpManageSearch.add(txtEmpManageSearch);

        btnEmpManageSearch.setText("Search");
        btnEmpManageSearch.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlEmpManageSearch.add(btnEmpManageSearch);

        pnlEmpManageCtrl.add(pnlEmpManageSearch, java.awt.BorderLayout.WEST);

        pnlEmpManageButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlEmpManageButtons.setOpaque(false);
        pnlEmpManageButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnEmpManageAdd.setText("Add Employee");
        btnEmpManageAdd.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlEmpManageButtons.add(btnEmpManageAdd);

        btnEmpManageEdit.setText("Edit Employee");
        btnEmpManageEdit.setEnabled(false);
        btnEmpManageEdit.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlEmpManageButtons.add(btnEmpManageEdit);

        btnEmpManageDelete.setText("Delete Employee");
        btnEmpManageDelete.setEnabled(false);
        btnEmpManageDelete.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlEmpManageButtons.add(btnEmpManageDelete);

        pnlEmpManageCtrl.add(pnlEmpManageButtons, java.awt.BorderLayout.EAST);

        pnlEmpManage.add(pnlEmpManageCtrl, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        tblEmpManageList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpManageList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblEmpManageList.setFillsViewportHeight(true);
        tblEmpManageList.setRowHeight(30);
        tblEmpManageList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEmpManageList);

        pnlEmpManage.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabHRModule.addTab("Employee Management", pnlEmpManage);

        pnlAttendanceRecords.setLayout(new java.awt.BorderLayout());

        pnlAttendanceRecCtrl.setBackground(new java.awt.Color(255, 255, 255));

        txtAttendanceSearch.setText("Employee ID");
        txtAttendanceSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        txtAttendanceSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAttendanceSearchKeyTyped(evt);
            }
        });
        pnlAttendanceRecCtrl.add(txtAttendanceSearch);

        drpAttendanceMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Month]", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        drpAttendanceMonth.setPreferredSize(new java.awt.Dimension(150, 30));
        drpAttendanceMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpAttendanceMonthActionPerformed(evt);
            }
        });
        pnlAttendanceRecCtrl.add(drpAttendanceMonth);

        drpAttendanceYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Year]", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        drpAttendanceYear.setPreferredSize(new java.awt.Dimension(150, 30));
        pnlAttendanceRecCtrl.add(drpAttendanceYear);

        pnlAttendanceRecords.add(pnlAttendanceRecCtrl, java.awt.BorderLayout.NORTH);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        tblAttendanceRec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tblAttendanceRec.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblAttendanceRec.setFillsViewportHeight(true);
        tblAttendanceRec.setRowHeight(30);
        tblAttendanceRec.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblAttendanceRec);

        pnlAttendanceRecords.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        tabHRModule.addTab("Attendance Records", pnlAttendanceRecords);

        pnlLeaveRecords.setLayout(new java.awt.BorderLayout());

        pnlLeaveRecCtrl.setBackground(new java.awt.Color(255, 255, 255));

        txtLeaveRecSearch.setText("Employee ID");
        txtLeaveRecSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        txtLeaveRecSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLeaveRecSearchKeyTyped(evt);
            }
        });
        pnlLeaveRecCtrl.add(txtLeaveRecSearch);

        drpLeaveRecMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Month]", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        drpLeaveRecMonth.setPreferredSize(new java.awt.Dimension(150, 30));
        drpLeaveRecMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpLeaveRecMonthActionPerformed(evt);
            }
        });
        pnlLeaveRecCtrl.add(drpLeaveRecMonth);

        drpLeaveRecYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Year]", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        drpLeaveRecYear.setPreferredSize(new java.awt.Dimension(150, 30));
        pnlLeaveRecCtrl.add(drpLeaveRecYear);

        drpLeaveRecStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Rejected", "All" }));
        drpLeaveRecStatus.setPreferredSize(new java.awt.Dimension(150, 30));
        pnlLeaveRecCtrl.add(drpLeaveRecStatus);
        pnlLeaveRecCtrl.add(pnlPLeaveRecVGlue9);

        pnlLeaveRecords.add(pnlLeaveRecCtrl, java.awt.BorderLayout.NORTH);

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setDividerLocation(350);
        jSplitPane1.setDividerSize(8);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane1.setOpaque(false);

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        tblLeaveRec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tblLeaveRec.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblLeaveRec.setFillsViewportHeight(true);
        tblLeaveRec.setRowHeight(30);
        tblLeaveRec.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLeaveRec.setShowGrid(true);
        tblLeaveRec.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(tblLeaveRec);

        jSplitPane1.setTopComponent(jScrollPane7);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        pnlLeaveRecMsg.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeaveRecMsg.setLayout(new java.awt.GridBagLayout());

        pnlLeaveRecReason.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeaveRecReason.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Reason", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15))); // NOI18N
        pnlLeaveRecReason.setMinimumSize(new java.awt.Dimension(10, 10));
        pnlLeaveRecReason.setOpaque(false);
        pnlLeaveRecReason.setLayout(new java.awt.BorderLayout());

        jScrollPane9.setBackground(new java.awt.Color(255, 255, 255));

        txtLeaveRecReason.setEditable(false);
        txtLeaveRecReason.setBackground(new java.awt.Color(255, 255, 255));
        txtLeaveRecReason.setLineWrap(true);
        txtLeaveRecReason.setRows(4);
        txtLeaveRecReason.setWrapStyleWord(true);
        txtLeaveRecReason.setBorder(null);
        txtLeaveRecReason.setFocusable(false);
        txtLeaveRecReason.setMinimumSize(new java.awt.Dimension(10, 10));
        jScrollPane9.setViewportView(txtLeaveRecReason);

        pnlLeaveRecReason.add(jScrollPane9, java.awt.BorderLayout.CENTER);

        vGlue12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vGlue12.setForeground(new java.awt.Color(30, 30, 30));
        vGlue12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vGlue12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlLeaveRecReason.add(vGlue12, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlLeaveRecMsg.add(pnlLeaveRecReason, gridBagConstraints);

        pnlLeaveRecDecision.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeaveRecDecision.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Decision", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15))); // NOI18N
        pnlLeaveRecDecision.setMinimumSize(new java.awt.Dimension(10, 10));
        pnlLeaveRecDecision.setOpaque(false);
        pnlLeaveRecDecision.setLayout(new java.awt.GridBagLayout());

        txtLeaveRecDecision.setEditable(false);
        txtLeaveRecDecision.setBackground(new java.awt.Color(255, 255, 255));
        txtLeaveRecDecision.setLineWrap(true);
        txtLeaveRecDecision.setRows(4);
        txtLeaveRecDecision.setWrapStyleWord(true);
        txtLeaveRecDecision.setBorder(null);
        txtLeaveRecDecision.setFocusable(false);
        txtLeaveRecDecision.setMinimumSize(new java.awt.Dimension(10, 10));
        jScrollPane10.setViewportView(txtLeaveRecDecision);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        pnlLeaveRecDecision.add(jScrollPane10, gridBagConstraints);

        jPanel4.setOpaque(false);

        btnLeaveRecApprove.setText("Approve");
        btnLeaveRecApprove.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel4.add(btnLeaveRecApprove);

        btnLeaveRecReject.setText("Reject");
        btnLeaveRecReject.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel4.add(btnLeaveRecReject);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlLeaveRecDecision.add(jPanel4, gridBagConstraints);

        vGlue13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vGlue13.setForeground(new java.awt.Color(30, 30, 30));
        vGlue13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vGlue13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlLeaveRecDecision.add(vGlue13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlLeaveRecMsg.add(pnlLeaveRecDecision, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        pnlLeaveRecMsg.add(pnlLeaveRecVGlue8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 20);
        jPanel3.add(pnlLeaveRecMsg, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel3);

        pnlLeaveRecords.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        tabHRModule.addTab("Leave Records", pnlLeaveRecords);

        pnlHRModule.add(tabHRModule, java.awt.BorderLayout.CENTER);

        add(pnlHRModule, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpManageSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpManageSearchKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_txtEmpManageSearchKeyTyped

    private void txtAttendanceSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAttendanceSearchKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_txtAttendanceSearchKeyTyped

    private void drpAttendanceMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpAttendanceMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpAttendanceMonthActionPerformed

    private void txtLeaveRecSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLeaveRecSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeaveRecSearchKeyTyped

    private void drpLeaveRecMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpLeaveRecMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpLeaveRecMonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpManageAdd;
    private javax.swing.JButton btnEmpManageDelete;
    private javax.swing.JButton btnEmpManageEdit;
    private javax.swing.JButton btnEmpManageSearch;
    private javax.swing.JButton btnLeaveRecApprove;
    private javax.swing.JButton btnLeaveRecReject;
    private javax.swing.JComboBox<String> drpAttendanceMonth;
    private javax.swing.JComboBox<String> drpAttendanceYear;
    private javax.swing.JComboBox<String> drpLeaveRecMonth;
    private javax.swing.JComboBox<String> drpLeaveRecStatus;
    private javax.swing.JComboBox<String> drpLeaveRecYear;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblEmpManageSearch;
    private javax.swing.JPanel pnlAttendanceRecCtrl;
    private javax.swing.JPanel pnlAttendanceRecords;
    private javax.swing.JPanel pnlEmpManage;
    private javax.swing.JPanel pnlEmpManageButtons;
    private javax.swing.JPanel pnlEmpManageCtrl;
    private javax.swing.JPanel pnlEmpManageSearch;
    private javax.swing.JPanel pnlHRModule;
    private javax.swing.JPanel pnlLeaveRecCtrl;
    private javax.swing.JPanel pnlLeaveRecDecision;
    private javax.swing.JPanel pnlLeaveRecMsg;
    private javax.swing.JPanel pnlLeaveRecReason;
    private javax.swing.JLabel pnlLeaveRecVGlue8;
    private javax.swing.JPanel pnlLeaveRecords;
    private javax.swing.JLabel pnlPLeaveRecVGlue9;
    private javax.swing.JTabbedPane tabHRModule;
    private javax.swing.JTable tblAttendanceRec;
    private javax.swing.JTable tblEmpManageList;
    private javax.swing.JTable tblLeaveRec;
    private javax.swing.JTextField txtAttendanceSearch;
    private javax.swing.JTextField txtEmpManageSearch;
    private javax.swing.JTextArea txtLeaveRecDecision;
    private javax.swing.JTextArea txtLeaveRecReason;
    private javax.swing.JTextField txtLeaveRecSearch;
    private javax.swing.JLabel vGlue12;
    private javax.swing.JLabel vGlue13;
    // End of variables declaration//GEN-END:variables
}
