/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Winter Melon
 */
public class ITModule extends javax.swing.JPanel {

    /**
     * Creates new form ITModule
     */
    public ITModule() {
        initComponents();
    }
    
    public javax.swing.JTabbedPane getTabPane() {
    return tabITModule; 
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabITModule = new javax.swing.JTabbedPane();
        pnlUserAccounts = new javax.swing.JPanel();
        pnlUserManageCtrl = new javax.swing.JPanel();
        pnlUserManageSearch = new javax.swing.JPanel();
        lblEmpManageSearch1 = new javax.swing.JLabel();
        txtEmpManageSearch1 = new javax.swing.JTextField();
        btnEmpManageSearch1 = new javax.swing.JButton();
        pnlUserManageButtons = new javax.swing.JPanel();
        btnUserAdd = new javax.swing.JButton();
        btnUserEdit = new javax.swing.JButton();
        btnUserDelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnlUserAccounts.setLayout(new java.awt.BorderLayout());

        pnlUserManageCtrl.setBackground(new java.awt.Color(255, 255, 255));
        pnlUserManageCtrl.setLayout(new java.awt.BorderLayout());

        pnlUserManageSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlUserManageSearch.setOpaque(false);
        pnlUserManageSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        lblEmpManageSearch1.setText("Search Employee ID:");
        pnlUserManageSearch.add(lblEmpManageSearch1);

        txtEmpManageSearch1.setText("Employee ID");
        txtEmpManageSearch1.setPreferredSize(new java.awt.Dimension(200, 30));
        txtEmpManageSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpManageSearch1KeyTyped(evt);
            }
        });
        pnlUserManageSearch.add(txtEmpManageSearch1);

        btnEmpManageSearch1.setText("Search");
        btnEmpManageSearch1.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlUserManageSearch.add(btnEmpManageSearch1);

        pnlUserManageCtrl.add(pnlUserManageSearch, java.awt.BorderLayout.WEST);

        pnlUserManageButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlUserManageButtons.setOpaque(false);
        pnlUserManageButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnUserAdd.setText("Register User");
        btnUserAdd.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlUserManageButtons.add(btnUserAdd);

        btnUserEdit.setText("Edit User");
        btnUserEdit.setEnabled(false);
        btnUserEdit.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlUserManageButtons.add(btnUserEdit);

        btnUserDelete.setText("Delete User");
        btnUserDelete.setEnabled(false);
        btnUserDelete.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlUserManageButtons.add(btnUserDelete);

        pnlUserManageCtrl.add(pnlUserManageButtons, java.awt.BorderLayout.EAST);

        pnlUserAccounts.add(pnlUserManageCtrl, java.awt.BorderLayout.NORTH);

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblUserAccounts);

        pnlUserAccounts.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabITModule.addTab("User Accounts", pnlUserAccounts);

        add(tabITModule, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpManageSearch1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpManageSearch1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpManageSearch1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpManageSearch1;
    private javax.swing.JButton btnUserAdd;
    private javax.swing.JButton btnUserDelete;
    private javax.swing.JButton btnUserEdit;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEmpManageSearch1;
    private javax.swing.JPanel pnlUserAccounts;
    private javax.swing.JPanel pnlUserManageButtons;
    private javax.swing.JPanel pnlUserManageCtrl;
    private javax.swing.JPanel pnlUserManageSearch;
    private javax.swing.JTabbedPane tabITModule;
    private javax.swing.JTable tblUserAccounts;
    private javax.swing.JTextField txtEmpManageSearch1;
    // End of variables declaration//GEN-END:variables
}
