package gui;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Winter Melon
 */

import java.util.List;

public class MainFrame extends javax.swing.JFrame {

    private String employeeId;
    private String role;
    private String fullName;
    private String position;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(String employeeId, String role) {
    initComponents();
    setLocationRelativeTo(null);
    
    this.employeeId = employeeId;
    this.role = role;
    
    updateButtonForRole();

    // Get employee's full name and position
    String[] info = getEmployeeNameAndPosition(employeeId);
    this.fullName = info[0];
    this.position = info[1];

    // Display welcome message
    lblFirstMessage.setText("Welcome " + fullName + " - " + position + "!");
    lblRole.setText(role + " access");

    if ("User".equalsIgnoreCase(role)) {
        btnViewEmployeeList.setText("View Employee Details");
        btnViewEmployeeList.removeActionListener(btnViewEmployeeList.getActionListeners()[0]);
        btnViewEmployeeList.addActionListener(e -> {
            new EmployeeDetailsFrame(employeeId).setVisible(true);
        });
    }
}
    
private String[] getEmployeeNameAndPosition(String employeeId) {
    List<String[]> employees = CSVHelper.loadEmployeeData();
    for (String[] emp : employees) {
        if (emp[0].equals(employeeId)) {
            String fullName = emp[2] + " " + emp[1]; // First + Last
            String position = emp[11];
            return new String[]{fullName, position};
        }
    }
    return new String[]{"Employee", "Unknown"};
}

private void updateButtonForRole() {
    if ("user".equalsIgnoreCase(role)) {
        btnViewEmployeeList.setText("View Employee Details");
    }
}

public MainFrame() {
    this("Unknown", "User");
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogo = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblFirstMessage = new javax.swing.JLabel();
        btnViewEmployeeList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/temp-logo2.gif"))); // NOI18N
        getContentPane().add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 540, -1));

        lblRole.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 0, 0));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRole.setText("Role");
        getContentPane().add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        lblFirstMessage.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblFirstMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFirstMessage.setText("= Welcome Message =");
        getContentPane().add(lblFirstMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 220, 530, -1));

        btnViewEmployeeList.setText("View Employee List");
        btnViewEmployeeList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btnViewEmployeeList.setMaximumSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.setMinimumSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.setPreferredSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeListActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEmployeeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MotorPH Portal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/login-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeListActionPerformed
        if ("user".equalsIgnoreCase(role)) {
            // Open only their own details
            new EmployeeDetailsFrame(employeeId).setVisible(true);
        } else {
            // Admin view: show full employee list
            new EmployeeListFrame().setVisible(true);
        }
    }//GEN-LAST:event_btnViewEmployeeListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewEmployeeList;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFirstMessage;
    private javax.swing.JLabel lblRole;
    // End of variables declaration//GEN-END:variables
}
