package gui;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Winter Melon
 */

import java.util.List;
import models.Departments;

public class MainFrame extends javax.swing.JFrame {

    private String currentEmpId;
    private models.Employee currentEmployee;
    private services.EmployeeServ employeeServ = new services.EmployeeServ();

    public MainFrame(String empId) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.currentEmpId = empId;
        loadEmployeeData();
               
    }

    public MainFrame() {
        this("10001");
    }
    
    private void loadEmployeeData() {
        this.currentEmployee = employeeServ.getEmployeeProfile(currentEmpId);
        
        if (currentEmployee != null) {
            lblRole.setText(currentEmployee.getDepartment().name());
            lblFirstMessage.setText("Welcome, " + currentEmployee.getFirstName() + "!");
        
            applyRBAC();
        
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Could not load employee details.");
        }
    }
    
    private void applyRBAC() {
    models.Departments dept = currentEmployee.getDepartment();
    
    // RBAC: Only HR and Admin can see the management button
    if (dept == Departments.HR || dept == Departments.ADMIN) {
            btnViewEmployeeList.setText("Manage Employees");
        } else {
            btnViewEmployeeList.setText("View My Details");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogo = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblFirstMessage = new javax.swing.JLabel();
        btnViewEmployeeList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/temp-logo2.gif"))); // NOI18N
        getContentPane().add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 540, -1));

        lblRole.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 0, 0));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRole.setText("Role");
        getContentPane().add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        lblFirstMessage.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblFirstMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFirstMessage.setText("= Welcome Message =");
        getContentPane().add(lblFirstMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 220, 530, -1));

        btnViewEmployeeList.setText("View Employee List");
        btnViewEmployeeList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btnViewEmployeeList.setMaximumSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.setMinimumSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.setPreferredSize(new java.awt.Dimension(140, 30));
        btnViewEmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeListActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEmployeeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MotorPH Portal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/login-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewEmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeListActionPerformed
        Departments dept = currentEmployee.getDepartment();
        
        if (dept == Departments.HR || dept == Departments.ADMIN) {
            new EmployeeListFrame().setVisible(true);
        } else {
            // Passes the logged-in ID to show only THEIR 19 columns
            new EmployeeDetailsFrame(currentEmpId).setVisible(true);
        }
    }//GEN-LAST:event_btnViewEmployeeListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewEmployeeList;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFirstMessage;
    private javax.swing.JLabel lblRole;
    // End of variables declaration//GEN-END:variables
}
