/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Winter Melon
 */
public class MainDashboard extends javax.swing.JFrame {

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblMotorPH = new javax.swing.JLabel();
        pnlNav = new javax.swing.JPanel();
        pnlNavEmployee = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnMyAttendance = new javax.swing.JButton();
        btnMyPayslip = new javax.swing.JButton();
        btnReqLeave = new javax.swing.JButton();
        pnlNavHR = new javax.swing.JPanel();
        btnManageEmp = new javax.swing.JButton();
        btnLeaveRec = new javax.swing.JButton();
        btnAttendanceRec = new javax.swing.JButton();
        pnlNavFinance = new javax.swing.JPanel();
        btnPayroll = new javax.swing.JButton();
        btnSalaryDetails = new javax.swing.JButton();
        btnStatutory = new javax.swing.JButton();
        pnlNavIT = new javax.swing.JPanel();
        btnUserAccounts = new javax.swing.JButton();
        btnSysLogs = new javax.swing.JButton();
        btnSysSettings = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlHeaderWest = new javax.swing.JPanel();
        lblBreadcrumb = new javax.swing.JLabel();
        pnlHeaderEast = new javax.swing.JPanel();
        pnlNameTag = new javax.swing.JPanel();
        lblNameTag = new javax.swing.JLabel();
        lblDeptTag = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlClock = new javax.swing.JPanel();
        lblClock = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        pnlWelcome = new javax.swing.JPanel();
        pnlWelcomeMsg = new javax.swing.JLabel();
        pnlClockInOut = new javax.swing.JPanel();
        lblClockStatus = new javax.swing.JLabel();
        btnClockIn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnClockOut = new javax.swing.JButton();
        pnlStats = new javax.swing.JPanel();
        pnlCardAttendance = new javax.swing.JPanel();
        lblCardAttendance = new javax.swing.JLabel();
        pnlCardNextPayday = new javax.swing.JPanel();
        lblCardNextPayday = new javax.swing.JLabel();
        pnlCardPendingLeaves = new javax.swing.JPanel();
        lblCardPendingLeaves = new javax.swing.JLabel();
        pnlRow3 = new javax.swing.JPanel();
        pnlAnnouncements = new javax.swing.JPanel();
        lblAnnouncements = new javax.swing.JLabel();
        pnlContact = new javax.swing.JPanel();
        pnlContact1 = new javax.swing.JPanel();
        lblContact = new javax.swing.JLabel();
        pnlContact2 = new javax.swing.JPanel();
        btnContactSupervisor = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnContactIT = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnContactHR = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btnContactFinance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSidebar.setBackground(new java.awt.Color(204, 255, 204));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(150, 700));
        pnlSidebar.setLayout(new java.awt.BorderLayout());

        pnlLogo.setBackground(new java.awt.Color(255, 204, 153));
        pnlLogo.setMinimumSize(new java.awt.Dimension(116, 75));
        pnlLogo.setPreferredSize(new java.awt.Dimension(116, 75));
        pnlLogo.setLayout(new java.awt.GridBagLayout());

        lblMotorPH.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMotorPH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotorPH.setText("MotorPH");
        pnlLogo.add(lblMotorPH, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlLogo, java.awt.BorderLayout.PAGE_START);

        pnlNav.setBackground(new java.awt.Color(255, 255, 204));
        pnlNav.setMaximumSize(new java.awt.Dimension(150, 32767));
        pnlNav.setLayout(new javax.swing.BoxLayout(pnlNav, javax.swing.BoxLayout.Y_AXIS));

        pnlNavEmployee.setMaximumSize(new java.awt.Dimension(150, 225));
        pnlNavEmployee.setMinimumSize(new java.awt.Dimension(150, 0));
        pnlNavEmployee.setLayout(new javax.swing.BoxLayout(pnlNavEmployee, javax.swing.BoxLayout.Y_AXIS));

        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDashboard.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnDashboard.setMaximumSize(new java.awt.Dimension(150, 45));
        btnDashboard.setMinimumSize(new java.awt.Dimension(150, 45));
        btnDashboard.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlNavEmployee.add(btnDashboard);

        btnMyProfile.setText("My Profile");
        btnMyProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMyProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMyProfile.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnMyProfile.setMaximumSize(new java.awt.Dimension(150, 45));
        btnMyProfile.setMinimumSize(new java.awt.Dimension(150, 45));
        btnMyProfile.setPreferredSize(new java.awt.Dimension(150, 45));
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });
        pnlNavEmployee.add(btnMyProfile);

        btnMyAttendance.setText("My Attendance");
        btnMyAttendance.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMyAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMyAttendance.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnMyAttendance.setMaximumSize(new java.awt.Dimension(150, 45));
        btnMyAttendance.setMinimumSize(new java.awt.Dimension(150, 45));
        btnMyAttendance.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlNavEmployee.add(btnMyAttendance);

        btnMyPayslip.setText("My Payslip");
        btnMyPayslip.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMyPayslip.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMyPayslip.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnMyPayslip.setMaximumSize(new java.awt.Dimension(150, 45));
        btnMyPayslip.setMinimumSize(new java.awt.Dimension(150, 45));
        btnMyPayslip.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlNavEmployee.add(btnMyPayslip);

        btnReqLeave.setText("Request Leave");
        btnReqLeave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReqLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReqLeave.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnReqLeave.setMaximumSize(new java.awt.Dimension(150, 45));
        btnReqLeave.setMinimumSize(new java.awt.Dimension(150, 45));
        btnReqLeave.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlNavEmployee.add(btnReqLeave);

        pnlNav.add(pnlNavEmployee);

        pnlNavHR.setMaximumSize(new java.awt.Dimension(150, 135));
        pnlNavHR.setMinimumSize(new java.awt.Dimension(150, 0));
        pnlNavHR.setLayout(new javax.swing.BoxLayout(pnlNavHR, javax.swing.BoxLayout.Y_AXIS));

        btnManageEmp.setText("Employee List");
        btnManageEmp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnManageEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnManageEmp.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnManageEmp.setMaximumSize(new java.awt.Dimension(150, 45));
        btnManageEmp.setMinimumSize(new java.awt.Dimension(150, 45));
        btnManageEmp.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlNavHR.add(btnManageEmp);

        btnLeaveRec.setText("Leave Requests");
        btnLeaveRec.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLeaveRec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLeaveRec.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnLeaveRec.setMaximumSize(new java.awt.Dimension(150, 45));
        btnLeaveRec.setMinimumSize(new java.awt.Dimension(150, 45));
        btnLeaveRec.setPreferredSize(new java.awt.Dimension(150, 45));
        btnLeaveRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveRecActionPerformed(evt);
            }
        });
        pnlNavHR.add(btnLeaveRec);

        btnAttendanceRec.setText("Attendance Records");
        btnAttendanceRec.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAttendanceRec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAttendanceRec.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnAttendanceRec.setMaximumSize(new java.awt.Dimension(150, 45));
        btnAttendanceRec.setMinimumSize(new java.awt.Dimension(150, 45));
        btnAttendanceRec.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlNavHR.add(btnAttendanceRec);

        pnlNav.add(pnlNavHR);

        pnlNavFinance.setMaximumSize(new java.awt.Dimension(150, 135));
        pnlNavFinance.setMinimumSize(new java.awt.Dimension(150, 0));
        pnlNavFinance.setLayout(new javax.swing.BoxLayout(pnlNavFinance, javax.swing.BoxLayout.Y_AXIS));

        btnPayroll.setText("Payroll");
        btnPayroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPayroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPayroll.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnPayroll.setMaximumSize(new java.awt.Dimension(150, 45));
        btnPayroll.setMinimumSize(new java.awt.Dimension(150, 45));
        btnPayroll.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlNavFinance.add(btnPayroll);

        btnSalaryDetails.setText("Salary Details");
        btnSalaryDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalaryDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalaryDetails.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnSalaryDetails.setMaximumSize(new java.awt.Dimension(150, 45));
        btnSalaryDetails.setMinimumSize(new java.awt.Dimension(150, 45));
        btnSalaryDetails.setPreferredSize(new java.awt.Dimension(150, 45));
        btnSalaryDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryDetailsActionPerformed(evt);
            }
        });
        pnlNavFinance.add(btnSalaryDetails);

        btnStatutory.setText("Deductions Table");
        btnStatutory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnStatutory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnStatutory.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnStatutory.setMaximumSize(new java.awt.Dimension(150, 45));
        btnStatutory.setMinimumSize(new java.awt.Dimension(150, 45));
        btnStatutory.setPreferredSize(new java.awt.Dimension(150, 45));
        btnStatutory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatutoryActionPerformed(evt);
            }
        });
        pnlNavFinance.add(btnStatutory);

        pnlNav.add(pnlNavFinance);

        pnlNavIT.setMaximumSize(new java.awt.Dimension(150, 135));
        pnlNavIT.setMinimumSize(new java.awt.Dimension(150, 0));
        pnlNavIT.setLayout(new javax.swing.BoxLayout(pnlNavIT, javax.swing.BoxLayout.Y_AXIS));

        btnUserAccounts.setText("User Accounts");
        btnUserAccounts.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUserAccounts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUserAccounts.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnUserAccounts.setMaximumSize(new java.awt.Dimension(150, 45));
        btnUserAccounts.setMinimumSize(new java.awt.Dimension(150, 45));
        btnUserAccounts.setPreferredSize(new java.awt.Dimension(150, 45));
        btnUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountsActionPerformed(evt);
            }
        });
        pnlNavIT.add(btnUserAccounts);

        btnSysLogs.setText("System Logs");
        btnSysLogs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSysLogs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSysLogs.setEnabled(false);
        btnSysLogs.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnSysLogs.setMaximumSize(new java.awt.Dimension(150, 45));
        btnSysLogs.setMinimumSize(new java.awt.Dimension(150, 45));
        btnSysLogs.setPreferredSize(new java.awt.Dimension(150, 45));
        btnSysLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysLogsActionPerformed(evt);
            }
        });
        pnlNavIT.add(btnSysLogs);

        btnSysSettings.setText("System Settings");
        btnSysSettings.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSysSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSysSettings.setEnabled(false);
        btnSysSettings.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnSysSettings.setMaximumSize(new java.awt.Dimension(150, 45));
        btnSysSettings.setMinimumSize(new java.awt.Dimension(150, 45));
        btnSysSettings.setPreferredSize(new java.awt.Dimension(150, 45));
        pnlNavIT.add(btnSysSettings);

        pnlNav.add(pnlNavIT);
        pnlNav.add(filler1);

        pnlSidebar.add(pnlNav, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.LINE_START);

        pnlMain.setBackground(new java.awt.Color(153, 153, 153));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 204));
        pnlHeader.setPreferredSize(new java.awt.Dimension(950, 50));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        pnlHeaderWest.setOpaque(false);
        pnlHeaderWest.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));

        lblBreadcrumb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBreadcrumb.setText("Breadcrumb");
        pnlHeaderWest.add(lblBreadcrumb);

        pnlHeader.add(pnlHeaderWest, java.awt.BorderLayout.WEST);

        pnlHeaderEast.setOpaque(false);
        pnlHeaderEast.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 10));

        pnlNameTag.setMinimumSize(new java.awt.Dimension(44, 20));
        pnlNameTag.setOpaque(false);

        lblNameTag.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNameTag.setText("Name");
        pnlNameTag.add(lblNameTag);

        lblDeptTag.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblDeptTag.setText("[DEPT]");
        pnlNameTag.add(lblDeptTag);

        pnlHeaderEast.add(pnlNameTag);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 30));
        pnlHeaderEast.add(jSeparator1);

        pnlClock.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlClock.setMinimumSize(new java.awt.Dimension(44, 20));

        lblClock.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lblClock.setText("HH:mm:ss");
        pnlClock.add(lblClock);

        pnlHeaderEast.add(pnlClock);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(2, 30));
        pnlHeaderEast.add(jSeparator2);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlHeaderEast.add(btnLogout);

        pnlHeader.add(pnlHeaderEast, java.awt.BorderLayout.EAST);

        pnlMain.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlContent.setBackground(new java.awt.Color(153, 255, 204));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlDashboard.setLayout(new javax.swing.BoxLayout(pnlDashboard, javax.swing.BoxLayout.Y_AXIS));

        pnlWelcome.setMaximumSize(new java.awt.Dimension(32767, 100));
        pnlWelcome.setLayout(new java.awt.BorderLayout());

        pnlWelcomeMsg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pnlWelcomeMsg.setText("Welcome, [NAME]!");
        pnlWelcome.add(pnlWelcomeMsg, java.awt.BorderLayout.WEST);

        lblClockStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblClockStatus.setText("Status: [Not Clocked In]");
        pnlClockInOut.add(lblClockStatus);

        btnClockIn.setText("Clock In");
        pnlClockInOut.add(btnClockIn);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(2, 30));
        pnlClockInOut.add(jSeparator3);

        btnClockOut.setText("Clock Out");
        pnlClockInOut.add(btnClockOut);

        pnlWelcome.add(pnlClockInOut, java.awt.BorderLayout.EAST);

        pnlDashboard.add(pnlWelcome);

        pnlStats.setBackground(new java.awt.Color(204, 255, 204));
        pnlStats.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        pnlStats.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        pnlCardAttendance.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardAttendance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(231, 231, 231), 2, true));
        pnlCardAttendance.setPreferredSize(new java.awt.Dimension(200, 100));
        pnlCardAttendance.setLayout(new java.awt.BorderLayout(10, 0));

        lblCardAttendance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCardAttendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCardAttendance.setText("Attendance:");
        lblCardAttendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCardAttendance.add(lblCardAttendance, java.awt.BorderLayout.NORTH);

        pnlStats.add(pnlCardAttendance);

        pnlCardNextPayday.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardNextPayday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(231, 231, 231), 2, true));
        pnlCardNextPayday.setPreferredSize(new java.awt.Dimension(200, 100));
        pnlCardNextPayday.setLayout(new java.awt.BorderLayout());

        lblCardNextPayday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCardNextPayday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCardNextPayday.setText("Next Payday:");
        lblCardNextPayday.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCardNextPayday.add(lblCardNextPayday, java.awt.BorderLayout.NORTH);

        pnlStats.add(pnlCardNextPayday);

        pnlCardPendingLeaves.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardPendingLeaves.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(231, 231, 231), 2, true));
        pnlCardPendingLeaves.setPreferredSize(new java.awt.Dimension(200, 100));
        pnlCardPendingLeaves.setLayout(new java.awt.BorderLayout());

        lblCardPendingLeaves.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCardPendingLeaves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCardPendingLeaves.setText("Pending Leaves:");
        lblCardPendingLeaves.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCardPendingLeaves.add(lblCardPendingLeaves, java.awt.BorderLayout.NORTH);

        pnlStats.add(pnlCardPendingLeaves);

        pnlDashboard.add(pnlStats);

        pnlRow3.setBackground(new java.awt.Color(204, 255, 204));
        pnlRow3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlRow3.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        pnlAnnouncements.setBackground(new java.awt.Color(255, 255, 255));
        pnlAnnouncements.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(231, 231, 231), 2, true));
        pnlAnnouncements.setPreferredSize(new java.awt.Dimension(200, 100));

        lblAnnouncements.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAnnouncements.setText("Company Announcements:");
        lblAnnouncements.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlAnnouncements.add(lblAnnouncements);

        pnlRow3.add(pnlAnnouncements);

        pnlContact.setBackground(new java.awt.Color(255, 255, 255));
        pnlContact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 2, true));
        pnlContact.setLayout(new javax.swing.BoxLayout(pnlContact, javax.swing.BoxLayout.Y_AXIS));

        pnlContact1.setOpaque(false);

        lblContact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContact.setText("Contact:");
        pnlContact1.add(lblContact);

        pnlContact.add(pnlContact1);

        pnlContact2.setOpaque(false);

        btnContactSupervisor.setText("Supervisor");
        pnlContact2.add(btnContactSupervisor);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setPreferredSize(new java.awt.Dimension(2, 30));
        pnlContact2.add(jSeparator4);

        btnContactIT.setText("IT");
        pnlContact2.add(btnContactIT);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(2, 30));
        pnlContact2.add(jSeparator5);

        btnContactHR.setText("HR");
        pnlContact2.add(btnContactHR);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setPreferredSize(new java.awt.Dimension(2, 30));
        pnlContact2.add(jSeparator6);

        btnContactFinance.setText("Finance");
        pnlContact2.add(btnContactFinance);

        pnlContact.add(pnlContact2);

        pnlRow3.add(pnlContact);

        pnlDashboard.add(pnlRow3);

        pnlContent.add(pnlDashboard, "card2");

        pnlMain.add(pnlContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMyProfileActionPerformed

    private void btnSysLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysLogsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSysLogsActionPerformed

    private void btnUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserAccountsActionPerformed

    private void btnLeaveRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeaveRecActionPerformed

    private void btnStatutoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatutoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatutoryActionPerformed

    private void btnSalaryDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalaryDetailsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendanceRec;
    private javax.swing.JButton btnClockIn;
    private javax.swing.JButton btnClockOut;
    private javax.swing.JButton btnContactFinance;
    private javax.swing.JButton btnContactHR;
    private javax.swing.JButton btnContactIT;
    private javax.swing.JButton btnContactSupervisor;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLeaveRec;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageEmp;
    private javax.swing.JButton btnMyAttendance;
    private javax.swing.JButton btnMyPayslip;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnPayroll;
    private javax.swing.JButton btnReqLeave;
    private javax.swing.JButton btnSalaryDetails;
    private javax.swing.JButton btnStatutory;
    private javax.swing.JButton btnSysLogs;
    private javax.swing.JButton btnSysSettings;
    private javax.swing.JButton btnUserAccounts;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblAnnouncements;
    private javax.swing.JLabel lblBreadcrumb;
    private javax.swing.JLabel lblCardAttendance;
    private javax.swing.JLabel lblCardNextPayday;
    private javax.swing.JLabel lblCardPendingLeaves;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblClockStatus;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDeptTag;
    private javax.swing.JLabel lblMotorPH;
    private javax.swing.JLabel lblNameTag;
    private javax.swing.JPanel pnlAnnouncements;
    private javax.swing.JPanel pnlCardAttendance;
    private javax.swing.JPanel pnlCardNextPayday;
    private javax.swing.JPanel pnlCardPendingLeaves;
    private javax.swing.JPanel pnlClock;
    private javax.swing.JPanel pnlClockInOut;
    private javax.swing.JPanel pnlContact;
    private javax.swing.JPanel pnlContact1;
    private javax.swing.JPanel pnlContact2;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeaderEast;
    private javax.swing.JPanel pnlHeaderWest;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNameTag;
    private javax.swing.JPanel pnlNav;
    private javax.swing.JPanel pnlNavEmployee;
    private javax.swing.JPanel pnlNavFinance;
    private javax.swing.JPanel pnlNavHR;
    private javax.swing.JPanel pnlNavIT;
    private javax.swing.JPanel pnlRow3;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlStats;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JLabel pnlWelcomeMsg;
    // End of variables declaration//GEN-END:variables
}
